# Use root/example as user/password credentials
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-east
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pmp1226
      MYSQL_DATABASE: eastwh
      MYSQL_USER: pmp
      MYSQL_PASSWORD: pmp1226
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network: